/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATM.Management;

/**
 *
 * @author user
 */
public class AllOption_Page extends javax.swing.JFrame {

    /**
     * Creates new form AllOption_Page
     */
    public AllOption_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DepositMBton = new javax.swing.JButton();
        ChangePinBton = new javax.swing.JButton();
        WithdrawBton = new javax.swing.JButton();
        TransferBton = new javax.swing.JButton();
        CheckBalanceBton = new javax.swing.JButton();
        InformationBton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("     ATM");

        DepositMBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DepositMBton.setText("Add Balance");
        DepositMBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositMBtonMouseClicked(evt);
            }
        });
        DepositMBton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositMBtonActionPerformed(evt);
            }
        });

        ChangePinBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChangePinBton.setText("Change Pin");
        ChangePinBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePinBtonMouseClicked(evt);
            }
        });

        WithdrawBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WithdrawBton.setText("Withdraw Money");
        WithdrawBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithdrawBtonMouseClicked(evt);
            }
        });

        TransferBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TransferBton.setText("Balance Transfer");
        TransferBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransferBtonMouseClicked(evt);
            }
        });

        CheckBalanceBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckBalanceBton.setText("Check Balance");
        CheckBalanceBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBalanceBtonMouseClicked(evt);
            }
        });

        InformationBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InformationBton.setText("Exit   ");
        InformationBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformationBtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepositMBton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WithdrawBton)
                            .addComponent(CheckBalanceBton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChangePinBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransferBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InformationBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePinBton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepositMBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransferBton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WithdrawBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InformationBton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBalanceBton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DepositMBtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositMBtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositMBtonActionPerformed

    private void CheckBalanceBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBalanceBtonMouseClicked
        // TODO add your handling code here:
        new Check_Balance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CheckBalanceBtonMouseClicked

    private void ChangePinBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePinBtonMouseClicked
        // TODO add your handling code here:
        new Change_Pin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangePinBtonMouseClicked

    private void WithdrawBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawBtonMouseClicked
        // TODO add your handling code here:
        new Select_Account_in_withDraw().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WithdrawBtonMouseClicked

    private void TransferBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferBtonMouseClicked
        // TODO add your handling code here:
        new Bank_Transfer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransferBtonMouseClicked

    private void InformationBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformationBtonMouseClicked
        // TODO add your handling code here:
        new HOME_Page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InformationBtonMouseClicked

    private void DepositMBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositMBtonMouseClicked
        // TODO add your handling code here:
        new Add_Balance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DepositMBtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllOption_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllOption_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllOption_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllOption_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllOption_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ChangePinBton;
    public javax.swing.JButton CheckBalanceBton;
    public javax.swing.JButton DepositMBton;
    public javax.swing.JButton InformationBton;
    public javax.swing.JButton TransferBton;
    public javax.swing.JButton WithdrawBton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
