/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATM.Management;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import org.apache.tomcat.jdbc.pool.DataSource;
import org.apache.tomcat.jdbc.pool.PoolProperties;
import java.sql.*;

/**
 *
 * @author user
 */
public class Bank_Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Bank_Transfer
     */
    public Bank_Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Transfer_Text1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Transfer_Text2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Transfer_text3 = new javax.swing.JTextField();
        Transfer_Bton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Transfer_Amount = new javax.swing.JTextField();
        Transfer_Bank_Bton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("   ATM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter ATM Number");

        Transfer_Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transfer_Text1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Account Number");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Enter Pin Number");

        Transfer_Bton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Transfer_Bton.setText("Transfer");
        Transfer_Bton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Transfer_BtonMouseClicked(evt);
            }
        });
        Transfer_Bton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transfer_BtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Enter Amount");

        Transfer_Bank_Bton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Transfer_Bank_Bton.setText("Back  ");
        Transfer_Bank_Bton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Transfer_Bank_BtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Transfer_Bank_Bton)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Transfer_Text1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(Transfer_Text2)
                            .addComponent(Transfer_text3)
                            .addComponent(Transfer_Amount))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(Transfer_Bton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Transfer_Bank_Bton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transfer_Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transfer_Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transfer_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Transfer_Amount, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addComponent(Transfer_Bton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Transfer_BtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transfer_BtonMouseClicked
        // TODO add your handling code here:
        java.util.Date d = new java.util.Date();
        
        Date dd = new Date(d.getTime());
        
        Time tt = new Time(d.getTime());
        
       Connection con = null;
       
         try{
         
        PoolProperties pp = new PoolProperties();
        pp.setDriverClassName("com.mysql.jdbc.Driver");
        pp.setUrl("jdbc:mysql://localhost:3306/ATM");
        pp.setUsername("root");
        pp.setPassword("Priyanshu@1234");
        pp.setMaxActive(100);
        pp.setInitialSize(50);
           DataSource ds = new DataSource();
        ds.setPoolProperties(pp);
        
         con = ds.getConnection();
          con.setAutoCommit(false);
        PreparedStatement ps = con.prepareStatement("insert into Transfer values(?,?,?,?,?,?)");
        ps.setString(1,Transfer_Text1.getText() );
        ps.setString(2, Transfer_Text2.getText());
        ps.setString(3, Transfer_text3.getText());
        ps.setString(4, Transfer_Amount.getText());
        ps.setDate(5, dd);
        ps.setTime(6, tt);
        
        
        int x = ps.executeUpdate();
        //-------------------------------------------------------------------------------------------------------//
        
        PreparedStatement ps1 = con.prepareStatement("select Amount from register where ATM_no=? and Pin=?");
        
        ps1.setString(1, Transfer_Text1.getText());
        ps1.setString(2, Transfer_text3.getText());
        
        ResultSet rs = ps1.executeQuery();
        int i = 0;
        int j = Integer.parseInt(Transfer_Amount.getText());
         //String s1 = "";
         
         if(rs.next()){
             i = Integer.parseInt(rs.getString(1));   
         }
         else{
             JOptionPane.showMessageDialog(rootPane, "enter correction information");
             new HOME_Page().setVisible(true);
             this.dispose();
         }
         
         
        //-------------------------------------------------------------------------------------------------------------------//
        
        PreparedStatement ps2 = con.prepareStatement("update register set Amount=? where Pin=?");
        int y = 0;
        if(j<=i){
            int k = i-j;
            String str = "" + k;
            ps2.setString(1, str);
            ps2.setString(2, Transfer_text3.getText());
            
            y = ps2.executeUpdate();
                    
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Insufficient balance");
        }
        
         
        if(x>0 && y>0){
            JOptionPane.showMessageDialog(null, "success");
            con.commit();
            new HOME_Page().setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Incorrecti information");
            con.rollback();
            new HOME_Page().setVisible(true);
            this.dispose();
        }
        
     }
        catch(HeadlessException | NumberFormatException | SQLException e){
            System.out.println(e);
             JOptionPane.showMessageDialog(null, "fill correct information");
             try{
                 con.rollback();
             }
             catch(SQLException ee){
                 
             }
             new HOME_Page().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_Transfer_BtonMouseClicked

    private void Transfer_Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transfer_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Transfer_Text1ActionPerformed

    private void Transfer_BtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transfer_BtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Transfer_BtonActionPerformed

    private void Transfer_Bank_BtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transfer_Bank_BtonMouseClicked
        // TODO add your handling code here:
        new AllOption_Page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Transfer_Bank_BtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bank_Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Transfer_Amount;
    public javax.swing.JButton Transfer_Bank_Bton;
    public javax.swing.JButton Transfer_Bton;
    public javax.swing.JTextField Transfer_Text1;
    public javax.swing.JTextField Transfer_Text2;
    public javax.swing.JTextField Transfer_text3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
