/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATM.Management;

import java.sql.Connection;
import javax.swing.JOptionPane;
import org.apache.tomcat.jdbc.pool.DataSource;
import org.apache.tomcat.jdbc.pool.PoolProperties;
import java.sql.*;
//import java.util.Date;


/**
 *
 * @author user
 */
public class Select_Amount extends javax.swing.JFrame {

    /**
     * Creates new form Select_Amount
     */
    public Select_Amount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Select_Amount_Text = new javax.swing.JTextField();
        Select_Amount_CashBton = new javax.swing.JButton();
        Select_Amount_BackBton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Select_Amount_PinText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("   ATM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Your Amount");

        Select_Amount_CashBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Select_Amount_CashBton.setText("Cash ");
        Select_Amount_CashBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Select_Amount_CashBtonMouseClicked(evt);
            }
        });

        Select_Amount_BackBton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Select_Amount_BackBton.setText("Back");
        Select_Amount_BackBton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Select_Amount_BackBtonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Your Pin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Select_Amount_BackBton)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Select_Amount_CashBton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Select_Amount_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(Select_Amount_PinText))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Select_Amount_BackBton))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_Amount_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_Amount_PinText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Select_Amount_CashBton)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Select_Amount_BackBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Select_Amount_BackBtonMouseClicked

        // TODO add your handling code here:
        new AllOption_Page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Select_Amount_BackBtonMouseClicked

    private void Select_Amount_CashBtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Select_Amount_CashBtonMouseClicked
        // TODO add your handling code here:
        String s = Select_Amount_Text.getText();
        java.util.Date d = new java.util.Date();
        
        Date dd = new Date(d.getTime());
        
        Time tt = new Time(d.getTime());
        
        
        
        int x = 0;
        try{
            x = Integer.parseInt(s);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Enter correct amount");
        }
        Login_Page text = new Login_Page();
        
        PoolProperties pp = new PoolProperties();
        pp.setDriverClassName("com.mysql.jdbc.Driver");
         pp.setUrl("jdbc:mysql://localhost:3306/ATM");
         pp.setUsername("root");
         pp.setPassword("Priyanshu@1234");
         
         DataSource ds = new DataSource();
         ds.setPoolProperties(pp);
         Connection con = null;
          String s1 = "";
         int y = 0;
         String s2 = "";
         try{
              con = ds.getConnection();
              con.setAutoCommit(false);
              PreparedStatement ps = con.prepareStatement("select Amount,ATM_no from register where Pin=?");
              
              ps.setString(1, Select_Amount_PinText.getText());
              
               ResultSet rs = ps.executeQuery();
               if(rs.next()){
               s1 = rs.getString(1);
                y = Integer.parseInt(s1);
                
                s2 = rs.getString(2);
                
                // get Account number from Database;
                
                   
               }
               
               
               if(y>=x){
                   int z = y - x;
                   String z1 = "" + z;
                   
                   PreparedStatement ps2 = con.prepareStatement("update register set Amount = ? where Pin=?");
                   ps2.setString(1, z1);
                   ps2.setString(2,Select_Amount_PinText.getText());
                   
                   int rowCount1 = ps2.executeUpdate();
                   
                   String saving = "Saving";
                   
                   PreparedStatement ps3 = con.prepareStatement("insert into Withdraw values(?,?,?,?,?,?)");
                   ps3.setString(1, s2);
                   ps3.setString(2, Select_Amount_PinText.getText());
                   ps3.setString(3, Select_Amount_Text.getText());
                   ps3.setString(4, saving);
                   ps3.setDate(5, dd);
                   ps3.setTime(6, tt);
                   
                   int rowCount2 = ps3.executeUpdate();
                   
                   
                   if(rowCount1>0&& rowCount2>0){
                       JOptionPane.showMessageDialog(rootPane, "successfully Transaction");
                       con.commit();
                       new HOME_Page().setVisible(true);
                       this.dispose();
                   }
                   else{
                       JOptionPane.showMessageDialog(rootPane, "Transaction Failed");
                       con.rollback();
                       new HOME_Page().setVisible(true);
                       this.dispose();
                   }
                   
                  
               }
               else{
                   JOptionPane.showMessageDialog(rootPane, "Enter correct amount");
                   con.rollback();
                       new HOME_Page().setVisible(true);
                       this.dispose();
               }
                       
              con.close();
              new HOME_Page().setVisible(true);
                       this.dispose();
              
              
         }
         catch(Exception e){
             System.err.println(e);
         }
    }//GEN-LAST:event_Select_Amount_CashBtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_Amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_Amount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Select_Amount_BackBton;
    public javax.swing.JButton Select_Amount_CashBton;
    public javax.swing.JTextField Select_Amount_PinText;
    public javax.swing.JTextField Select_Amount_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
